<<<<<<< HEAD
2016/04/10 16:36:50 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`riwayat_penyakit`, CONSTRAINT `fk_riwayatpenyakit_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `riwayat_penyakit` (`nip_santri`, `nama_penyakit`, `tanggal`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 16:36:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`riwayat_penyakit`, CONSTRAINT `fk_riwayatpenyakit_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `riwayat_penyakit` (`nip_santri`, `nama_penyakit`, `tanggal`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): RiwayatPenyakitController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('riwayatPenyakit...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php?r=riwayatPenyakit/create
HTTP_REFERER=http://localhost/siadm/index.php?r=riwayatPenyakit/create
---
2016/04/10 14:01:17 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.Nama Pengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CComponent->__get('Nama Pengguna')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(LoginForm), 'Nama Pengguna')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(LoginForm), 'Nama Pengguna', Array)
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginForm), 'Nama Pengguna', Array)
#4 C:\xampp\htdocs\siadm\protected\views\site\login.php(29): CActiveForm->textField(Object(LoginForm), 'Nama Pengguna')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(98): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/siadm/index.php?r=site/login
---
2016/04/11 01:39:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/login
---
2016/04/11 01:39:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UserLogin".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UserLogin')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UserLogin
---
2016/04/11 01:40:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/login
---
2016/04/11 01:40:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "loginform".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('loginform')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/loginform
---
2016/04/11 01:48:15 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 01:48:15 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 01:48:19 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 01:48:19 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 01:48:25 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 01:48:25 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 01:49:23 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 01:49:23 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 01:49:31 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 01:49:31 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 03:30:43 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 03:30:43 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 03:31:05 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 03:31:05 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
=======
>>>>>>> master
2016/04/18 06:22:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri/delete')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri/delete/?ajax=santri-grid
HTTP_REFERER=http://localhost/siadm/index.php/Santri/index
---
2016/04/18 06:22:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri/create')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri/create
HTTP_REFERER=http://localhost/siadm/index.php/Santri/index
---
2016/04/18 06:23:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri/create')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri/create
HTTP_REFERER=http://localhost/siadm/index.php/Santri/index
---
2016/04/18 06:23:12 [error] [php] Undefined variable: model (C:\xampp\htdocs\siadm\protected\views\pencatatanPelanggaran\index.php:18)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): PencatatanPelanggaranController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): PencatatanPelanggaranController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(134): PencatatanPelanggaranController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PencatatanPelanggaranController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PencatatanPelanggaranController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): PencatatanPelanggaranController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PencatatanPelanggaranController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/PencatatanPelanggaran
in C:\xampp\htdocs\siadm\protected\views\pencatatanPelanggaran\index.php (18)
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (134)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/18 06:23:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Perizinan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Perizinan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/Perizinan
HTTP_REFERER=http://localhost/siadm/index.php/prestasi
---
2016/04/18 06:23:21 [error] [php] include(Pelanggaran.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(165): model()
#2 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(87): CActiveDataProvider->getModel()
#3 C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php(131): CActiveDataProvider->__construct()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PelanggaranController->actionIndex()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PelanggaranController->runAction()
#7 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#9 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PelanggaranController->filterAccessControl()
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(265): PelanggaranController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PelanggaranController->run()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/pelanggaran
in C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php (131)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/18 06:26:07 [error] [exception.CException] exception 'CException' with message 'Property "PencatatanPerizinan.deskripsi" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('deskripsi')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('deskripsi')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(PencatatanPerizinan), 'deskripsi')
#3 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(PencatatanPerizinan), 'deskripsi', Array)
#4 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(PencatatanPerizinan), 'deskripsi', Array)
#5 C:\xampp\htdocs\siadm\protected\views\pencatatanPerizinan\_search.php(26): CActiveForm->textField(Object(PencatatanPerizinan), 'deskripsi', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\siadm\protected\views\pencatatanPerizinan\index.php(15): CController->renderPartial('_search', Array)
#10 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#14 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php(134): CController->render('index', Array)
#15 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPerizinanController->actionIndex()
#16 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#25 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('PencatatanPeriz...')
#26 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#27 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/siadm/index.php/PencatatanPerizinan
HTTP_REFERER=http://localhost/siadm/index.php/RiwayatPenyakit
---
2016/04/18 06:26:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Perizinan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Perizinan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/Perizinan
HTTP_REFERER=http://localhost/siadm/index.php/RiwayatPenyakit
---
2016/04/18 06:26:11 [error] [php] include(Pelanggaran.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(165): model()
#2 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(87): CActiveDataProvider->getModel()
#3 C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php(131): CActiveDataProvider->__construct()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PelanggaranController->actionIndex()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PelanggaranController->runAction()
#7 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#9 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PelanggaranController->filterAccessControl()
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(265): PelanggaranController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PelanggaranController->run()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/pelanggaran
in C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php (131)
in C:\xampp\htdocs\siadm\index.php (13)
