2016/05/14 10:45:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "unduh".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('unduh')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('unduh')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Santri/unduh/in...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/Santri/unduh/index
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 10:46:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "unduh".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('unduh')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('unduh')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Santri/unduh/in...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/Santri/unduh/index
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 10:46:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "unduh".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('unduh')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('unduh')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Santri/unduh/un...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/Santri/unduh/unduh-data-santri
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 11:18:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UnduhLaporanTotal".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UnduhLaporanTot...')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UnduhLaporanTotal
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 11:18:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UnduhLaporanTotal".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UnduhLaporanTot...')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UnduhLaporanTotal
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 11:20:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UnduhLaporanTotal".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UnduhLaporanTot...')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UnduhLaporanTotal
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 11:20:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LaporanKeuangan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('LaporanKeuangan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/LaporanKeuangan
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/14 11:20:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UnduhLaporanKeuangan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UnduhLaporanKeu...')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UnduhLaporanKeuangan
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/17 07:01:17 [warning] [application] Failed to set unsafe attribute "cari_tanggal_awal" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:01:17 [warning] [application] Failed to set unsafe attribute "cari_tanggal_akhir" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:01:18 [warning] [application] Failed to set unsafe attribute "cari_tanggal_awal" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:01:18 [warning] [application] Failed to set unsafe attribute "cari_tanggal_akhir" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:01:22 [warning] [application] Failed to set unsafe attribute "cari_tanggal_awal" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:01:22 [warning] [application] Failed to set unsafe attribute "cari_tanggal_akhir" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:02:23 [warning] [application] Failed to set unsafe attribute "cari_tanggal_awal" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/17 07:02:23 [warning] [application] Failed to set unsafe attribute "cari_tanggal_akhir" of "PencatatanPerizinan".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPerizinanController.php (203)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 03:15:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LaporanKeuangan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('LaporanKeuangan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/LaporanKeuangan
HTTP_REFERER=http://localhost/siadm/index.php/pemasukkanDonatur/create
---
2016/05/18 03:16:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LaporanKeuangan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('LaporanKeuangan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/LaporanKeuangan
HTTP_REFERER=http://localhost/siadm/index.php/pemasukkanDonatur/create
---
2016/05/18 03:26:17 [error] [php] Undefined variable: model (C:\xampp\htdocs\siadm\protected\views\donatur\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): DonaturController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): DonaturController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php(130): DonaturController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): DonaturController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): DonaturController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): DonaturController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): DonaturController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): DonaturController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(33): CWebApplication->run()
REQUEST_URI=/siadm/index.php/Donatur
in C:\xampp\htdocs\siadm\protected\views\donatur\index.php (22)
in C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php (130)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 10:52:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UnduhTransaksiPengeluaran".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('UnduhTransaksiP...')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/UnduhTransaksiPengeluaran
HTTP_REFERER=http://localhost/siadm/index.php/Donatur
---
2016/05/18 11:11:15 [warning] [application] Failed to set unsafe attribute "id" of "Donatur".
in C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:12:02 [warning] [application] Failed to set unsafe attribute "id" of "Donatur".
in C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:12:57 [warning] [application] Failed to set unsafe attribute "id" of "Donatur".
in C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:16:57 [warning] [application] Failed to set unsafe attribute "id" of "Donatur".
in C:\xampp\htdocs\siadm\protected\controllers\DonaturController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:23:12 [warning] [application] Failed to set unsafe attribute "id" of "Kelas".
in C:\xampp\htdocs\siadm\protected\controllers\KelasController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:24:43 [warning] [application] Failed to set unsafe attribute "id" of "Kelas".
in C:\xampp\htdocs\siadm\protected\controllers\KelasController.php (74)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:29:29 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:31:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/user/19
HTTP_REFERER=http://localhost/siadm/index.php/user/update/19
---
2016/05/18 11:31:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/user/update/19
HTTP_REFERER=http://localhost/siadm/index.php/User
---
2016/05/18 11:31:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('User')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/User
HTTP_REFERER=http://localhost/siadm/index.php/site/index
---
2016/05/18 11:37:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('create')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/create
HTTP_REFERER=http://localhost/siadm/index.php/MataPelajaran/create
---
2016/05/18 11:38:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('create')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/create
HTTP_REFERER=http://localhost/siadm/index.php/MataPelajaran/create
---
2016/05/18 11:38:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "unduh".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('unduh')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/unduh
HTTP_REFERER=http://localhost/siadm/index.php/MataPelajaran/admin
---
2016/05/18 11:45:38 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '111' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `santri` (`nip`, `nis`, `nik`, `nisn`, `nama_lengkap`, `nama_kecil`, `status`, `alamat`, `jenjang`, `tempat_lahir`, `tanggal_lahir`, `golongan_darah`, `anak_ke`, `jum_saudara`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13).
in C:\xampp\htdocs\siadm\protected\controllers\SantriController.php (95)
in C:\xampp\htdocs\siadm\index.php (33)
2016/05/18 11:45:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '111' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `santri` (`nip`, `nis`, `nik`, `nisn`, `nama_lengkap`, `nama_kecil`, `status`, `alamat`, `jenjang`, `tempat_lahir`, `tanggal_lahir`, `golongan_darah`, `anak_ke`, `jum_saudara`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\SantriController.php(95): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SantriController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('Santri/create')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/Santri/create
HTTP_REFERER=http://localhost/siadm/index.php/Santri/create
---
