2016/05/24 22:52:13 [error] [exception.CException] exception 'CException' with message 'Class name "Log" does not match class file "C:\xampp\htdocs\siadm\protected\models\Log.php".' in C:\xampp\htdocs\yii\YiiBase.php:423
Stack trace:
#0 [internal function]: YiiBase::autoload('Log')
#1 C:\xampp\htdocs\siadm\protected\models\Base.php(14): spl_autoload_call('Log')
#2 C:\xampp\htdocs\siadm\protected\models\Base.php(29): Base->log('Create User dat...')
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1100): Base->afterSave()
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#5 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(141): CActiveRecord->save()
#6 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): UserController->actionIndex()
#7 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('User')
#17 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#19 {main}
REQUEST_URI=/siadm/index.php/User
HTTP_REFERER=http://localhost/siadm/index.php/User
---
2016/05/24 22:54:51 [error] [exception.CException] exception 'CException' with message 'Class name "Log" does not match class file "C:\xampp\htdocs\siadm\protected\models\Log.php".' in C:\xampp\htdocs\yii\YiiBase.php:423
Stack trace:
#0 [internal function]: YiiBase::autoload('Log')
#1 C:\xampp\htdocs\siadm\protected\models\Base.php(14): spl_autoload_call('Log')
#2 C:\xampp\htdocs\siadm\protected\models\Base.php(29): Base->log('Create User dat...')
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1100): Base->afterSave()
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#5 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(141): CActiveRecord->save()
#6 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): UserController->actionIndex()
#7 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('User')
#17 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#19 {main}
REQUEST_URI=/siadm/index.php/User
HTTP_REFERER=http://localhost/siadm/index.php/User
---
2016/05/24 22:57:47 [error] [exception.CException] exception 'CException' with message 'Class name "Log" does not match class file "C:\xampp\htdocs\siadm\protected\models\Log.php".' in C:\xampp\htdocs\yii\YiiBase.php:423
Stack trace:
#0 [internal function]: YiiBase::autoload('Log')
#1 C:\xampp\htdocs\siadm\protected\models\Base.php(14): spl_autoload_call('Log')
#2 C:\xampp\htdocs\siadm\protected\models\Base.php(29): Base->log('Create RiwayatP...')
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1100): Base->afterSave()
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#5 C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php(82): CActiveRecord->save()
#6 [internal function]: RiwayatPenyakitController->actionCreate(NULL)
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(RiwayatPenyakitController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(RiwayatPenyakitController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('RiwayatPenyakit...')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/RiwayatPenyakit/create
HTTP_REFERER=http://localhost/siadm/index.php/RiwayatPenyakit/create
---
2016/05/24 22:59:14 [error] [exception.CException] exception 'CException' with message 'Class name "Log" does not match class file "C:\xampp\htdocs\siadm\protected\models\Log.php".' in C:\xampp\htdocs\yii\YiiBase.php:423
Stack trace:
#0 [internal function]: YiiBase::autoload('Log')
#1 C:\xampp\htdocs\siadm\protected\models\Base.php(14): spl_autoload_call('Log')
#2 C:\xampp\htdocs\siadm\protected\models\Base.php(29): Base->log('Update RiwayatP...')
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1129): Base->afterSave()
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->update(NULL)
#5 C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php(106): CActiveRecord->save()
#6 [internal function]: RiwayatPenyakitController->actionUpdate('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(RiwayatPenyakitController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(RiwayatPenyakitController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('riwayatPenyakit...')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(33): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/riwayatPenyakit/update/1
HTTP_REFERER=http://localhost/siadm/index.php/riwayatPenyakit/update/1
---
