2016/04/11 04:29:28 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'admin')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
