2016/04/20 10:08:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php:165
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(57): MataPelajaranController->loadModel('975')
#1 [internal function]: MataPelajaranController->actionView('975')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(MataPelajaranController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(MataPelajaranController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('MataPelajaran/v...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/MataPelajaran/975
HTTP_REFERER=http://localhost/siadm/index.php/mataPelajaran/index
---
2016/04/20 10:20:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('PencatatanPeriz...')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/PencatatanPerizinan
---
2016/04/20 10:23:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('MataPelajaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/MataPelajaran
HTTP_REFERER=http://localhost/siadm/index.php/mataPelajaran/admin
---
2016/04/20 10:24:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('MataPelajaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/MataPelajaran
---
2016/04/20 10:28:46 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('MataPelajaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/MataPelajaran
---
2016/04/20 10:29:17 [error] [php] Undefined variable: data (C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php:24)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): MataPelajaranController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): MataPelajaranController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): MataPelajaranController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): MataPelajaranController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): MataPelajaranController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): MataPelajaranController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): MataPelajaranController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/MataPelajaran
in C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php (24)
in C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php (143)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/20 10:31:29 [error] [php] Undefined variable: data (C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php:24)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): MataPelajaranController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): MataPelajaranController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): MataPelajaranController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): MataPelajaranController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): MataPelajaranController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): MataPelajaranController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): MataPelajaranController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/MataPelajaran
in C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php (24)
in C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php (143)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/20 11:00:26 [error] [exception.CException] exception 'CException' with message 'Property "CLinkColumn.name" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('name', 'nama')
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(52): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 11:01:04 [error] [exception.CException] exception 'CException' with message 'Property "CLinkColumn.name" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('name', 'nama')
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(52): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 11:01:17 [error] [exception.CException] exception 'CException' with message 'Property "CDataColumn.labelExpression" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('labelExpression', '$data->nama')
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(51): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 11:01:18 [error] [exception.CException] exception 'CException' with message 'Property "CDataColumn.labelExpression" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('labelExpression', '$data->nama')
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(51): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 11:01:19 [error] [exception.CException] exception 'CException' with message 'Property "CDataColumn.labelExpression" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('labelExpression', '$data->nama')
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(51): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 11:02:15 [error] [exception.CException] exception 'CException' with message 'Property "CDataColumn.0" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\YiiBase.php(220): CComponent->__set('0', Array)
#1 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\yii\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\siadm\protected\views\mataPelajaran\index.php(54): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\siadm\protected\controllers\MataPelajaranController.php(143): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): MataPelajaranController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
---
2016/04/20 14:56:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('mataPelajaran/i...')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/mataPelajaran/index
HTTP_REFERER=http://localhost/siadm/index.php/mataPelajaran/create
---
2016/04/28 16:02:55 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/user/update/12
---
2016/04/28 16:12:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/user/update/12
---
2016/05/03 03:43:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "perizinan".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('perizinan')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/perizinan
---
2016/05/03 03:43:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:26:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:27:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sita".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('sita')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/sita
---
2016/05/03 12:27:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "daksjlakkkkkkkkkkkkkkkkkkkkkk".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('daksjlakkkkkkkk...')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('daksjlakkkkkkkk...')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/daksjlakkk...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/site/daksjlakkkkkkkkkkkkkkkkkkkkkk
---
2016/05/03 12:27:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "daksjlakkkkkkkkkkkkkkkkkkkkkk".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('daksjlakkkkkkkk...')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('daksjlakkkkkkkk...')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/daksjlakkk...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/site/daksjlakkkkkkkkkkkkkkkkkkkkkk
---
2016/05/03 12:28:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:31:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:33:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:35:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:35:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:35:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:35:55 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:37:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:43:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:43:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/03 12:43:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pelanggarans".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggarans')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/pelanggarans
---
2016/05/03 12:44:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pelanggarans".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggarans')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/pelanggarans
---
2016/05/04 17:51:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 17:52:03 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 17:53:11 [error] [php] include(Pelanggaran.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(165): model()
#2 C:\xampp\htdocs\yii\web\CActiveDataProvider.php(87): CActiveDataProvider->getModel()
#3 C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php(131): CActiveDataProvider->__construct()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PelanggaranController->actionIndex()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PelanggaranController->runAction()
#7 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#9 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PelanggaranController->filterAccessControl()
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(265): PelanggaranController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PelanggaranController->run()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/pelanggaran
in C:\xampp\htdocs\siadm\protected\controllers\PelanggaranController.php (131)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:19:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 18:20:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:22:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:22:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:22:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:24:55 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:26:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:32:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('santri')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/santri
---
2016/05/04 18:34:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/prestasi
---
2016/05/04 18:44:21 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:45:45 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:45:49 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:45:53 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:46:16 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:46:17 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:50:05 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:52:43 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 18:59:48 [error] [php] Missing argument 3 for CHtml::listData(), called in C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\_form.php on line 27 and defined (C:\xampp\htdocs\yii\web\helpers\CHtml.php:2271)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(95): PencatatanPelanggaranController->renderInternal()
#1 C:\xampp\htdocs\yii\web\CController.php(869): PencatatanPelanggaranController->renderFile()
#2 C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\create.php(18): PencatatanPelanggaranController->renderPartial()
#3 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(95): PencatatanPelanggaranController->renderInternal()
#5 C:\xampp\htdocs\yii\web\CController.php(869): PencatatanPelanggaranController->renderFile()
#6 C:\xampp\htdocs\yii\web\CController.php(782): PencatatanPelanggaranController->renderPartial()
#7 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(93): PencatatanPelanggaranController->render()
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionCreate()
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PencatatanPelanggaranController->runAction()
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PencatatanPelanggaranController->filterAccessControl()
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): PencatatanPelanggaranController->runActionWithFilters()
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PencatatanPelanggaranController->run()
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/PencatatanPelanggaran/create
in C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\_form.php (27)
in C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\create.php (18)
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (93)
2016/05/04 19:06:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 19:08:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 19:08:55 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "PencatatanPelanggaran".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (150)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 19:09:07 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "PencatatanPelanggaran".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (150)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 19:09:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 19:34:33 [error] [php] include(nip.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2341): call_user_func()
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2279): value()
#3 C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\_form.php(27): listData()
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): PencatatanPelanggaranController->renderInternal()
#6 C:\xampp\htdocs\yii\web\CController.php(869): PencatatanPelanggaranController->renderFile()
#7 C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\create.php(18): PencatatanPelanggaranController->renderPartial()
#8 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#9 C:\xampp\htdocs\yii\web\CBaseController.php(95): PencatatanPelanggaranController->renderInternal()
#10 C:\xampp\htdocs\yii\web\CController.php(869): PencatatanPelanggaranController->renderFile()
#11 C:\xampp\htdocs\yii\web\CController.php(782): PencatatanPelanggaranController->renderPartial()
#12 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(95): PencatatanPelanggaranController->render()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionCreate()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PencatatanPelanggaranController->runAction()
#16 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PencatatanPelanggaranController->filterAccessControl()
#19 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\yii\web\CController.php(265): PencatatanPelanggaranController->runActionWithFilters()
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PencatatanPelanggaranController->run()
#23 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#25 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/PencatatanPelanggaran/create
in C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\_form.php (27)
in C:\xampp\htdocs\siadm\protected\views\PencatatanPelanggaran\create.php (18)
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (95)
2016/05/04 20:16:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pelanggaran')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/pelanggaran
---
2016/05/04 20:29:28 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`nip_santri`, `deskripsi`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (89)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 20:29:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`nip_santri`, `deskripsi`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(89): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('PencatatanPelan...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/PencatatanPelanggaran/create
HTTP_REFERER=http://localhost/siadm/index.php/PencatatanPelanggaran/create
---
2016/05/04 20:30:16 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "PencatatanPelanggaran".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (150)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 20:30:25 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`nip_santri`, `deskripsi`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (89)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/04 20:30:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`nip_santri`, `deskripsi`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(89): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pencatatanPelan...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/pencatatanPelanggaran/create/5678
HTTP_REFERER=http://localhost/siadm/index.php/pencatatanPelanggaran/create/5678
---
2016/05/04 20:33:03 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "PencatatanPelanggaran".
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (150)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/05 16:55:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "unduh".' in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('unduh')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siadm/index.php/unduh
---
2016/05/05 17:25:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(UserWeb), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('User')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siadm/index.php/User
---
2016/05/07 15:20:37 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/07 16:11:21 [warning] [application] Failed to set unsafe attribute "nama_lengkap" of "Prestasi".
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (139)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/07 16:27:59 [error] [exception.CException] exception 'CException' with message 'Property "Prestasi.sql" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('sql')
#1 C:\xampp\htdocs\siadm\protected\views\prestasi\view.php(19): CActiveRecord->__get('sql')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(63): CController->render('view', Array)
#7 [internal function]: PrestasiController->actionView('1')
#8 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 16:28:55 [error] [php] Undefined variable: sql (C:\xampp\htdocs\siadm\protected\views\prestasi\view.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): PrestasiController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): PrestasiController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(63): PrestasiController->render()
#3 unknown(0): PrestasiController->actionView()
#4 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PrestasiController->runAction()
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PrestasiController->filterAccessControl()
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): PrestasiController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PrestasiController->run()
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/prestasi/1
in C:\xampp\htdocs\siadm\protected\views\prestasi\view.php (19)
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (63)
in C:\xampp\htdocs\siadm\index.php (13)
2016/05/07 16:29:22 [error] [exception.CException] exception 'CException' with message 'Property "Prestasi.SELECT nama_lengkap FROM SANTRI s, PRESTASI p WHERE s.nip=p.nip_santri" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('SELECT nama_len...')
#1 C:\xampp\htdocs\siadm\protected\views\prestasi\view.php(20): CActiveRecord->__get('SELECT nama_len...')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(63): CController->render('view', Array)
#7 [internal function]: PrestasiController->actionView('1')
#8 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 16:43:39 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nama". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nama', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:18:25 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nama". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nama', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:19:50 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nipSantri2". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nipSantri2', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:20:35 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nipSantri2". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nipSantri2', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:20:45 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nipSantri2". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nipSantri2', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:20:47 [error] [exception.CDbException] exception 'CDbException' with message 'Active record "Prestasi" has an invalid configuration for relation "nipSantri2". It must specify the relation type, the related active record class and the foreign key.' in C:\xampp\htdocs\yii\db\ar\CActiveRecord.php:2436
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(2415): CActiveRecordMetaData->addRelation('nipSantri2', Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Prestasi))
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#4 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(171): CActiveRecord->findByPk('1')
#5 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(62): PrestasiController->loadModel('1')
#6 [internal function]: PrestasiController->actionView('1')
#7 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PrestasiController), Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PrestasiController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/view')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/index.php/prestasi/1
---
2016/05/07 18:21:04 [error] [php] Undefined variable: nip_santri (C:\xampp\htdocs\siadm\protected\views\prestasi\view.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): PrestasiController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): PrestasiController->renderPartial()
#2 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(63): PrestasiController->render()
#3 unknown(0): PrestasiController->actionView()
#4 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): PrestasiController->runAction()
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): PrestasiController->filterAccessControl()
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): PrestasiController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): PrestasiController->run()
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/prestasi/1
in C:\xampp\htdocs\siadm\protected\views\prestasi\view.php (19)
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (63)
in C:\xampp\htdocs\siadm\index.php (13)
